// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIVrqjv5Q3i82cF2geQySdz3HQ2KbD6c4',
    appId: '1:842877656899:web:ad0ff0722ee9f22f4a19f6',
    messagingSenderId: '842877656899',
    projectId: 'nbluganda',
    authDomain: 'nbluganda.firebaseapp.com',
    databaseURL: 'https://nbluganda-default-rtdb.firebaseio.com',
    storageBucket: 'nbluganda.appspot.com',
    measurementId: 'G-6ZDJZJ6P05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZRvNXIbunYabxMSKh_Xp8RGxeh02OzvU',
    appId: '1:842877656899:android:108310c292024e924a19f6',
    messagingSenderId: '842877656899',
    projectId: 'nbluganda',
    databaseURL: 'https://nbluganda-default-rtdb.firebaseio.com',
    storageBucket: 'nbluganda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEpSCO4NfXXNKWGGX41QLuxuPpffNojfo',
    appId: '1:842877656899:ios:f351f1666ccee3ab4a19f6',
    messagingSenderId: '842877656899',
    projectId: 'nbluganda',
    databaseURL: 'https://nbluganda-default-rtdb.firebaseio.com',
    storageBucket: 'nbluganda.appspot.com',
    iosBundleId: 'com.example.nbl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEpSCO4NfXXNKWGGX41QLuxuPpffNojfo',
    appId: '1:842877656899:ios:f351f1666ccee3ab4a19f6',
    messagingSenderId: '842877656899',
    projectId: 'nbluganda',
    databaseURL: 'https://nbluganda-default-rtdb.firebaseio.com',
    storageBucket: 'nbluganda.appspot.com',
    iosBundleId: 'com.example.nbl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIVrqjv5Q3i82cF2geQySdz3HQ2KbD6c4',
    appId: '1:842877656899:web:66eaa58660c147b14a19f6',
    messagingSenderId: '842877656899',
    projectId: 'nbluganda',
    authDomain: 'nbluganda.firebaseapp.com',
    databaseURL: 'https://nbluganda-default-rtdb.firebaseio.com',
    storageBucket: 'nbluganda.appspot.com',
    measurementId: 'G-WWD5LHEQV9',
  );
}
